#!/bin/sh
# Reassign ownership of the console to root, this should disallow
# assignment of console output to any random users's xterm
#
chmod 622 /dev/console
chown root /dev/console

# file location /usr/local/lib/X11/xdm/
# enable logout/restart/shutdown from pekwm's menu
OPT=`cat /var/tmp/xdm_exit`
: > /var/tmp/xdm_exit

case ${OPT} in
	1);;	# logout
	2) shutdown -r now;;
	3) shutdown -p now;;
	#*) shutdown -p now;;
esac

exit 0
